# Generated by Django 4.0.4 on 2022-04-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='level',
            field=models.CharField(choices=[('one', 'one'), ('two', 'two'), ('Four', 'Four'), ('Five', 'Five'), ('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight'), ('Nine', 'Nine'), ('Ten', 'Ten'), ('Eleven', 'Eleven'), ('Twelve', 'Twelve')], max_length=50),
        ),
    ]
